name: Preview Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Required for gh-pages deployment
      pull-requests: write  # Required for commenting
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        env:
          BASE_PATH: /api-showcase/pr-preview/${{ github.event.pull_request.number }}
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: pr-preview/${{ github.event.pull_request.number }}
          
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.name}/pr-preview/${context.issue.number}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `🚀 Preview deployment is ready!\n\nPreview: ${previewUrl}`
            })